#!/bin/bash

# colors taken from tokyonight theme
red="0xfff7768e"
blue="0xff7aa2f7"
transparent="0x00000000"
grey="0xff414550"

options=(
  style=round
  width=6.0
  hidpi=on
  active_color="$blue"
  inactive_color="$transparent"
  blacklist="espanso,Todoist,SoundSource,Todoist Helper,TodoistWidgets,Tailscale,Sleeve,PastePal,Dropover"
)

borders "${options[@]}"
