#!/bin/bash

options=(
	# style=round
	# width=6.0
	# hidpi=off
	# active_color=0xffe2e2e3
	# inactive_color=0xff414550
  # blacklist="Todoist","SoundSource","Todoist Helper", "TodoistWidgets","Tailscale","Sleeve", "PastePal", "Dropover"
)


borders "${options[@]}" 

# active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0