# to update run 'chezmoi apply, -R to refresh externals'

[".cli-plugins/zsh/zsh-autosuggestions"]
type = "archive"
url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
exclude = [
  "*/.editorconfig",
  "*/.gitattributes",
  "*/.github",
  "*/.gitignore",
  "*/*.md",
  "*/*.circleci",
]

[".cli-plugins/zsh/zsh-syntax-highlighting"]
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"
exclude = [
  "*/.editorconfig",
  "*/.gitattributes",
  "*/.github",
  "*/.gitignore",
  "*/*.md",
]

[".cli-plugins/fzf/fzf-git.sh"]
type = "git-repo"
url = "https://github.com/junegunn/fzf.git"
refreshPeriod = "168h"
exclude = [
  "*/.editorconfig",
  "*/.gitattributes",
  "*/.github",
  "*/.gitignore",
  "*/*.md",
]

[".fzf"]
type = "file"
url = "https://github.com/junegunn/fzf-git.sh/raw/main/fzf-git.sh"
exact = true
stripComponents = 1
refreshPeriod = "168h"
exclude = [
  "*/.editorconfig",
  "*/.gitattributes",
  "*/.github",
  "*/.gitignore",
  "*/*.md",
]
