# ------------------------------------------
# defaults
# ------------------------------------------

# Start AeroSpace at login
start-at-login = true
after-login-command = []
after-startup-command = ['exec-and-forget borders']

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 60
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']


# ------------------------------------------
# layout control
# ------------------------------------------

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget

# toggle fullscreen
alt-f = 'fullscreen'

# reset sizes
alt-shift-r = 'balance-sizes'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'


# ------------------------------------------
# workspaces
# ------------------------------------------
# See:  https://nikitabobko.github.io/AeroSpace/commands#workspace, aerospace list-apps

alt-1 = 'workspace 1-browser'
#raycast: alt+b = browser

alt-2 = 'workspace 2-code'
#raycast:
# - alt+c = editor
# - alt+a = primary ai model
# - alt+shift+a = secondary ai model
# - hyper+a = ai wrapper (boltai, etc.)
# - alt+t = terminal

alt-3 = 'workspace 3-email'
# raycast: alt+m = mail

alt-4 = 'workspace 4-files'

alt-5 = 'workspace 5-docs'

alt-6 = 'workspace 6-misc1'
alt-7 = 'workspace 7-misc2'

alt-8 = 'workspace 8-notes'
# raycast: alt+o = obsidian, alt+shift+n = notion, alt+shift+t = todoist

alt-9 = 'workspace 9-music'
# raycast: alt+y = spotify


# --- globals ---

ctrl-alt-left = 'workspace prev'
ctrl-alt-right = 'workspace next'

alt-tab = 'workspace-back-and-forth'

alt-shift-semicolon = 'mode service'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = ['move-node-to-workspace 1-browser', 'workspace 1-browser']
alt-shift-2 = ['move-node-to-workspace 2-code', 'workspace 2-code']
alt-shift-3 = ['move-node-to-workspace 3-email', 'workspace 3-email']
alt-shift-4 = ['move-node-to-workspace 4-files', 'workspace 4-files']
alt-shift-5 = ['move-node-to-workspace 5-docs', 'workspace 5-docs']
alt-shift-6 = ['move-node-to-workspace 6-misc1', 'workspace 6-misc1']
alt-shift-7 = ['move-node-to-workspace 7-misc2', 'workspace 7-misc2']
alt-shift-8 = ['move-node-to-workspace 8-notes', 'workspace 8-notes']
alt-shift-9 = ['move-node-to-workspace 9-music', 'workspace 9-music']


# ------------------------------------------
# service mode (default)
# ------------------------------------------
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = [
  'layout floating tiling',
  'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']


# ------------------------------------------
# window detection
# ------------------------------------------

# --- 1. browser ---
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace 1-browser'

# --- 2. code ---
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 2-code'

# --- 3. email / work ---
[[on-window-detected]]
if.app-id = 'com.mimestream.Mimestream'
run = 'move-node-to-workspace 3-email'

[[on-window-detected]]
if.app-id = 'notion.id'
run = 'move-node-to-workspace 3-email'

[[on-window-detected]]
if.app-id = 'com.invoiceninja.app'
run = 'move-node-to-workspace 3-email'

# --- 4. files ---
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'move-node-to-workspace 4-files'

# --- 5. docs ---
[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = 'move-node-to-workspace 5-docs'

[[on-window-detected]]
if.app-id = 'com.microsoft.Word'
run = 'move-node-to-workspace 5-docs'

# --- 6. misc1 ---
[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 6-misc1'

# --- 8. notes ---
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace 8-notes'

[[on-window-detected]]
if.app-id = 'com.todoist.mac.Todoist'
if.window-title-regex-substring = '^(Today|Upcoming|Inbox|Filters & Labels|.*\(Todoist\))$'
run = 'move-node-to-workspace 8-notes'

# --- 9. music ---
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 9-music'

# --- excluded apps

# itsyhome
[[on-window-detected]]
if.app-id = 'com.nickustinov.itsyhome'
run = ['layout floating']

# orbstack
[[on-window-detected]]
if.app-id = 'dev.kdrag0n.MacVirt'
run = ['layout floating']
